### POST create a new category
POST http://localhost:3000/categories
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSm9obiBEb2UiLCJlbWFpbCI6ImpvaG5AZXhhbXBsZS5jb20iLCJpYXQiOjE3NjE3MTQ5MjksImV4cCI6MTc2MTgwMTMyOX0.h03KsMaT18nvmnHEp__b0_5EC2aJZnPKyHO4mxYct2E

{
  "name": "Foods"
}

### GET all categories
GET http://localhost:3000/categories?name=foods&page=1&size=10
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSm9obiBEb2UiLCJlbWFpbCI6ImpvaG5AZXhhbXBsZS5jb20iLCJpYXQiOjE3NjE3MTQ5MjksImV4cCI6MTc2MTgwMTMyOX0.h03KsMaT18nvmnHEp__b0_5EC2aJZnPKyHO4mxYct2E

### GET category by id
GET http://localhost:3000/categories/b5817177-31f1-40d1-b1a3-6b3fb1671f51
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSm9obiBEb2UiLCJlbWFpbCI6ImpvaG5AZXhhbXBsZS5jb20iLCJpYXQiOjE3NjE3MTQ5MjksImV4cCI6MTc2MTgwMTMyOX0.h03KsMaT18nvmnHEp__b0_5EC2aJZnPKyHO4mxYct2E
