###

### POST register a new user
POST http://localhost:3000/register
Content-Type: application/json
Authorization: Bearer [jwt_token]

{
  "name": "User",
  "email": "user2@example.com",
  "password": "password"
}

###

### POST login
POST http://localhost:3000/login
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "password"
}

###
